services:
  - type: web
    name: aiflix-backend
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn aiflix.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: aiflix.settings
      - key: DEBUG
        value: False
      - fromDatabase:
          name: aiflix-db
          property: connectionString
      - key: HF_API_TOKEN
        sync: false
      - key: TMDB_API_KEY
        sync: false

databases:
  - name: aiflix-db
