# Generated by Django 3.2.25 on 2025-06-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='genre_thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie_posters/')),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('release_year', models.IntegerField()),
                ('actors', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('award_count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('genres', models.ManyToManyField(to='movies.Genre')),
            ],
        ),
    ]
